import type { Metadata } from "next";
import { ReactNode } from "react";
import { redirect } from "next/navigation";
import authGuard from "@/utils/auth-guard";

export const metadata: Metadata = {
    title: "Artists",
    description: "Generated by create next app",
};

export default async function ArtistsLayout({ children }: { children: ReactNode }) {
    const session = await authGuard();
    if (!session) redirect("/");
    return <>{children}</>;
}
